#:schema node_modules/wrangler/config-schema.json
name = "worker"
main = "../../worker/src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

base_dir = "./"
find_additional_modules = true

rules = [
    { type = "Text", globs = ["config.json"], fallthrough = false }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
